<?php
/**
 * p4-pricing JSON -> MariaDB full upsert SQL generator
 *
 * 사용법:
 *   php docs2/generate_full_insert_from_p4_pricing.php \
 *     --input=/absolute/path/p4-pricing.json \
 *     --output=/absolute/path/pricing_full_upsert.sql \
 *     --profile-id=1
 *
 * 입력 JSON 형식:
 *   src/App.jsx 의 DEF_PRICING 구조와 동일한 객체
 */

declare(strict_types=1);

ini_set('display_errors', '1');
error_reporting(E_ALL);

function argValue(string $name, ?string $default = null): ?string
{
    global $argv;
    foreach ($argv as $a) {
        if (str_starts_with($a, "--{$name}=")) {
            return substr($a, strlen($name) + 3);
        }
    }
    return $default;
}

function sqlString(?string $v): string
{
    if ($v === null) return 'NULL';
    $escaped = str_replace("'", "''", $v);
    return "'{$escaped}'";
}

function sqlNum($v): string
{
    if ($v === null || $v === '') return 'NULL';
    if (is_bool($v)) return $v ? '1' : '0';
    if (is_numeric($v)) return (string)$v;
    return 'NULL';
}

function requireKey(array $arr, string $key): void
{
    if (!array_key_exists($key, $arr)) {
        fwrite(STDERR, "[ERROR] missing key: {$key}\n");
        exit(1);
    }
}

$input = argValue('input');
$output = argValue('output');
$profileId = (int)(argValue('profile-id', '1') ?? '1');

if (!$input || !$output) {
    fwrite(STDERR, "Usage:\n");
    fwrite(STDERR, "  php docs2/generate_full_insert_from_p4_pricing.php --input=/path/p4-pricing.json --output=/path/pricing_full_upsert.sql [--profile-id=1]\n");
    exit(1);
}

if (!is_file($input)) {
    fwrite(STDERR, "[ERROR] input file not found: {$input}\n");
    exit(1);
}

$raw = file_get_contents($input);
if ($raw === false) {
    fwrite(STDERR, "[ERROR] failed to read input file\n");
    exit(1);
}

$pricing = json_decode($raw, true);
if (!is_array($pricing)) {
    fwrite(STDERR, "[ERROR] invalid JSON input\n");
    exit(1);
}

// 필수 키 체크
foreach ([
    'printTypes',
    'printTable',
    'sideRate',
    'coverPrintRate',
    'innerPapers',
    'coverPapers',
    'coatingTable',
    'bindingTypes',
    'bindingTable',
    'endpapers',
    'postProc',
] as $k) {
    requireKey($pricing, $k);
}

$sql = [];
$sql[] = "-- Auto-generated by generate_full_insert_from_p4_pricing.php";
$sql[] = "-- Source: {$input}";
$sql[] = "-- Profile ID: {$profileId}";
$sql[] = "SET NAMES utf8mb4;";
$sql[] = "USE bookmoa;";
$sql[] = "START TRANSACTION;";
$sql[] = "";

// profile 보장
$sql[] = "INSERT INTO pricing_profiles (id, name, is_active)";
$sql[] = "VALUES ({$profileId}, '기본 가격표', 1)";
$sql[] = "ON DUPLICATE KEY UPDATE name = VALUES(name), is_active = VALUES(is_active);";
$sql[] = "";

// 기존 profile 데이터 삭제 후 재적재 (일관성 보장)
$deleteTables = [
    'pricing_print_types',
    'pricing_print_table',
    'pricing_side_rate',
    'pricing_cover_print_rate',
    'pricing_inner_papers',
    'pricing_cover_papers',
    'pricing_coating_table',
    'pricing_binding_types',
    'pricing_binding_table',
    'pricing_endpapers',
    'pricing_postproc',
];

foreach ($deleteTables as $tbl) {
    $sql[] = "DELETE FROM {$tbl} WHERE profile_id = {$profileId};";
}
$sql[] = "";

// print types
if (!empty($pricing['printTypes']) && is_array($pricing['printTypes'])) {
    $rows = [];
    foreach ($pricing['printTypes'] as $i => $pt) {
        $rows[] = "({$profileId}, " . sqlString((string)$pt) . ", " . (int)$i . ")";
    }
    $sql[] = "INSERT INTO pricing_print_types (profile_id, print_type, sort_order) VALUES";
    $sql[] = "  " . implode(",\n  ", $rows) . ";";
    $sql[] = "";
}

// print table
if (!empty($pricing['printTable']) && is_array($pricing['printTable'])) {
    $rows = [];
    foreach ($pricing['printTable'] as $r) {
        $counter = (int)($r['c'] ?? 0);
        $vals = $r['v'] ?? [];
        foreach ($pricing['printTypes'] as $idx => $pt) {
            $v = $vals[$idx] ?? null;
            $rows[] = "("
                . "{$profileId}, {$counter}, " . sqlString((string)$pt) . ", " . sqlNum($v)
                . ")";
        }
    }
    if ($rows) {
        $sql[] = "INSERT INTO pricing_print_table (profile_id, counter_c, print_type, unit_price) VALUES";
        $sql[] = "  " . implode(",\n  ", $rows) . ";";
        $sql[] = "";
    }
}

// side rate
if (is_array($pricing['sideRate'])) {
    $rows = [];
    foreach ($pricing['sideRate'] as $side => $v) {
        $rows[] = "({$profileId}, " . sqlString((string)$side) . ", " . sqlNum($v) . ")";
    }
    if ($rows) {
        $sql[] = "INSERT INTO pricing_side_rate (profile_id, side_name, unit_price) VALUES";
        $sql[] = "  " . implode(",\n  ", $rows) . ";";
        $sql[] = "";
    }
}

// cover print rate
if (is_array($pricing['coverPrintRate'])) {
    $rows = [];
    foreach ($pricing['coverPrintRate'] as $side => $v) {
        $rows[] = "({$profileId}, " . sqlString((string)$side) . ", " . sqlNum($v) . ")";
    }
    if ($rows) {
        $sql[] = "INSERT INTO pricing_cover_print_rate (profile_id, side_name, unit_price) VALUES";
        $sql[] = "  " . implode(",\n  ", $rows) . ";";
        $sql[] = "";
    }
}

// inner papers
if (is_array($pricing['innerPapers'])) {
    $rows = [];
    foreach ($pricing['innerPapers'] as $paperName => $sizes) {
        if (!is_array($sizes)) continue;
        foreach ($sizes as $sizeCode => $v) {
            $rows[] = "("
                . "{$profileId}, " . sqlString((string)$paperName) . ", " . sqlString((string)$sizeCode) . ", " . sqlNum($v)
                . ")";
        }
    }
    if ($rows) {
        $sql[] = "INSERT INTO pricing_inner_papers (profile_id, paper_name, size_code, unit_price) VALUES";
        $sql[] = "  " . implode(",\n  ", $rows) . ";";
        $sql[] = "";
    }
}

// cover papers
if (is_array($pricing['coverPapers'])) {
    $rows = [];
    foreach ($pricing['coverPapers'] as $paperName => $sizes) {
        if (!is_array($sizes)) continue;
        foreach ($sizes as $sizeCode => $v) {
            $rows[] = "("
                . "{$profileId}, " . sqlString((string)$paperName) . ", " . sqlString((string)$sizeCode) . ", " . sqlNum($v)
                . ")";
        }
    }
    if ($rows) {
        $sql[] = "INSERT INTO pricing_cover_papers (profile_id, paper_name, size_code, unit_price) VALUES";
        $sql[] = "  " . implode(",\n  ", $rows) . ";";
        $sql[] = "";
    }
}

// coating table
if (is_array($pricing['coatingTable'])) {
    $rows = [];
    foreach ($pricing['coatingTable'] as $coverSize => $coatMap) {
        if (!is_array($coatMap)) continue;
        foreach ($coatMap as $coatType => $v) {
            $rows[] = "("
                . "{$profileId}, " . sqlString((string)$coverSize) . ", " . sqlString((string)$coatType) . ", " . sqlNum($v)
                . ")";
        }
    }
    if ($rows) {
        $sql[] = "INSERT INTO pricing_coating_table (profile_id, cover_size, coating_type, unit_price) VALUES";
        $sql[] = "  " . implode(",\n  ", $rows) . ";";
        $sql[] = "";
    }
}

// binding types
if (!empty($pricing['bindingTypes']) && is_array($pricing['bindingTypes'])) {
    $rows = [];
    foreach ($pricing['bindingTypes'] as $i => $bt) {
        $rows[] = "({$profileId}, " . sqlString((string)$bt) . ", " . (int)$i . ")";
    }
    $sql[] = "INSERT INTO pricing_binding_types (profile_id, binding_type, sort_order) VALUES";
    $sql[] = "  " . implode(",\n  ", $rows) . ";";
    $sql[] = "";
}

// binding table
if (!empty($pricing['bindingTable']) && is_array($pricing['bindingTable'])) {
    $rows = [];
    foreach ($pricing['bindingTable'] as $r) {
        $qty = (int)($r['q'] ?? 0);
        $vals = $r['v'] ?? [];
        foreach ($pricing['bindingTypes'] as $idx => $bt) {
            $v = $vals[$idx] ?? 0;
            $rows[] = "("
                . "{$profileId}, {$qty}, " . sqlString((string)$bt) . ", " . sqlNum($v)
                . ")";
        }
    }
    if ($rows) {
        $sql[] = "INSERT INTO pricing_binding_table (profile_id, qty_q, binding_type, unit_price) VALUES";
        $sql[] = "  " . implode(",\n  ", $rows) . ";";
        $sql[] = "";
    }
}

// endpapers
if (is_array($pricing['endpapers'])) {
    $rows = [];
    foreach ($pricing['endpapers'] as $endpaperName => $formatMap) {
        if (!is_array($formatMap)) continue;
        foreach ($formatMap as $formatCode => $v) {
            $rows[] = "("
                . "{$profileId}, " . sqlString((string)$endpaperName) . ", " . sqlString((string)$formatCode) . ", " . sqlNum($v)
                . ")";
        }
    }
    if ($rows) {
        $sql[] = "INSERT INTO pricing_endpapers (profile_id, endpaper_name, format_code, unit_price) VALUES";
        $sql[] = "  " . implode(",\n  ", $rows) . ";";
        $sql[] = "";
    }
}

// postproc
if (is_array($pricing['postProc'])) {
    $rows = [];
    foreach ($pricing['postProc'] as $procName => $v) {
        $rows[] = "("
            . "{$profileId}, " . sqlString((string)$procName) . ", " . sqlNum($v)
            . ")";
    }
    if ($rows) {
        $sql[] = "INSERT INTO pricing_postproc (profile_id, proc_name, unit_price) VALUES";
        $sql[] = "  " . implode(",\n  ", $rows) . ";";
        $sql[] = "";
    }
}

$sql[] = "INSERT INTO migration_logs (stage_name, source_key, total_count, success_count, fail_count, message)";
$sql[] = "VALUES ('pricing-etl', 'p4-pricing', NULL, NULL, NULL, " . sqlString("pricing full upsert generated from {$input}") . ");";
$sql[] = "";
$sql[] = "COMMIT;";
$sql[] = "";
$sql[] = "-- done.";

$finalSql = implode("\n", $sql) . "\n";
$ok = file_put_contents($output, $finalSql);
if ($ok === false) {
    fwrite(STDERR, "[ERROR] failed to write output file: {$output}\n");
    exit(1);
}

fwrite(STDOUT, "[OK] SQL generated: {$output}\n");
fwrite(STDOUT, "[OK] profile_id={$profileId}\n");

